/**
 * Sample Visitor Data
 * 
 * This file contains sample user data for testing the mapbox globe viewer.
 * In a production application, this data would come from an API or database.
 * 
 * Each visitor object should include:
 * - Geographic coordinates (latitude, longitude)
 * - User identification (visitorId, firstName, lastName, email)
 * - Location information (city, country, countryCode)
 * - Optional: profileImage, device info, browser info, etc.
 */
export const sampleVisitors = [
  {
    visitorId: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    latitude: 40.7128,
    longitude: -74.0060,
    city: 'New York',
    country: 'United States',
    countryCode: 'US',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    isCustomer: true,
    device: { type: 'desktop' },
    browser: { name: 'Chrome' },
    os: { name: 'Windows' },
    referrer: 'Google',
    currentUrl: '/products/laptop',
    conversionLikelihood: { score: 85 }
  },
  {
    visitorId: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    latitude: 51.5074,
    longitude: -0.1278,
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    isCustomer: false,
    device: { type: 'mobile' },
    browser: { name: 'Safari' },
    os: { name: 'iOS' },
    referrer: 'Direct',
    currentUrl: '/home',
    conversionLikelihood: { score: 42 }
  },
  {
    visitorId: '3',
    firstName: 'Hiroshi',
    lastName: 'Tanaka',
    email: 'hiroshi.tanaka@example.com',
    latitude: 35.6895,
    longitude: 139.6917,
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hiroshi',
    isCustomer: true,
    device: { type: 'desktop' },
    browser: { name: 'Firefox' },
    os: { name: 'macOS' },
    referrer: 'Bing',
    currentUrl: '/products/phone',
    conversionLikelihood: { score: 92 }
  },
  {
    visitorId: '4',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@example.com',
    latitude: 40.4168,
    longitude: -3.7038,
    city: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    isCustomer: false,
    device: { type: 'tablet' },
    browser: { name: 'Chrome' },
    os: { name: 'Android' },
    referrer: 'Facebook',
    currentUrl: '/blog',
    conversionLikelihood: { score: 28 }
  },
  {
    visitorId: '5',
    firstName: 'Ahmed',
    lastName: 'Ali',
    email: 'ahmed.ali@example.com',
    latitude: 30.0444,
    longitude: 31.2358,
    city: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    profileImage: null,
    isCustomer: false,
    device: { type: 'mobile' },
    browser: { name: 'Chrome' },
    os: { name: 'Android' },
    referrer: 'Direct',
    currentUrl: '/about',
    conversionLikelihood: { score: 15 }
  },
  {
    visitorId: '6',
    firstName: 'Li',
    lastName: 'Wei',
    email: 'li.wei@example.com',
    latitude: 39.9042,
    longitude: 116.4074,
    city: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    profileImage: null,
    isCustomer: true,
    device: { type: 'desktop' },
    browser: { name: 'Edge' },
    os: { name: 'Windows' },
    referrer: 'Baidu',
    currentUrl: '/products/tablet',
    conversionLikelihood: { score: 78 }
  },
  {
    visitorId: '7',
    firstName: 'Sophie',
    lastName: 'Martin',
    email: 'sophie.martin@example.com',
    latitude: 48.8566,
    longitude: 2.3522,
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    isCustomer: false,
    device: { type: 'desktop' },
    browser: { name: 'Safari' },
    os: { name: 'macOS' },
    referrer: 'Twitter',
    currentUrl: '/contact',
    conversionLikelihood: { score: 35 }
  },
  {
    visitorId: '8',
    firstName: 'Carlos',
    lastName: 'Silva',
    email: 'carlos.silva@example.com',
    latitude: -23.5505,
    longitude: -46.6333,
    city: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    isCustomer: true,
    device: { type: 'mobile', icon: null },
    browser: { name: 'Chrome', icon: null },
    os: { name: 'Android', icon: null },
    referrer: 'Instagram',
    referrerImage: null,
    currentUrl: '/products/watch',
    conversionLikelihood: { score: 88 }
  },
  {
    visitorId: '9',
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@example.com',
    latitude: -33.8688,
    longitude: 151.2093,
    city: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    isCustomer: false,
    device: { type: 'desktop' },
    browser: { name: 'Chrome' },
    os: { name: 'Windows' },
    referrer: 'Google',
    currentUrl: '/pricing',
    conversionLikelihood: { score: 55 }
  },
  {
    visitorId: '10',
    firstName: 'Raj',
    lastName: 'Patel',
    email: 'raj.patel@example.com',
    latitude: 19.0760,
    longitude: 72.8777,
    city: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    profileImage: null,
    isCustomer: false,
    device: { type: 'mobile' },
    browser: { name: 'Chrome' },
    os: { name: 'Android' },
    referrer: 'Direct',
    currentUrl: '/faq',
    conversionLikelihood: { score: 22 }
  },
  {
    visitorId: '11',
    firstName: 'Anna',
    lastName: 'Kowalski',
    email: 'anna.kowalski@example.com',
    latitude: 52.2297,
    longitude: 21.0122,
    city: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna',
    isCustomer: true,
    device: { type: 'desktop' },
    browser: { name: 'Firefox' },
    os: { name: 'Linux' },
    referrer: 'LinkedIn',
    currentUrl: '/products/headphones',
    conversionLikelihood: { score: 95 }
  },
  {
    visitorId: '12',
    firstName: 'Mohammed',
    lastName: 'Al-Rashid',
    email: 'mohammed.alrashid@example.com',
    latitude: 24.7136,
    longitude: 46.6753,
    city: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    profileImage: null,
    isCustomer: false,
    device: { type: 'tablet' },
    browser: { name: 'Safari' },
    os: { name: 'iOS' },
    referrer: 'Direct',
    currentUrl: '/support',
    conversionLikelihood: { score: 18 }
  }
]

